### ISSUE TITLE
Dependency conflict: fastapi version is 0.1.17

### ISSUE THREAD

**Issue by k4black** [starlite-api/api-performance-tests#5]
## Problem 

Currenty (17 Oct 2022) there are a conflict in `starlette` version: 
* latest `fastapi` requires `starlette==0.20.4`
* latest `starlite` requires `starlette>=0.21`

Which causes unintended resolution installing `fastapi==0.1.17` (check `poetry.lock` file).  

This cannot be called an honest comparison in any case.

## Suggestion 

Consider the option of launching benchmarks in docker. This will completely remove the dependency problem and completely isolate each of the current (or future) frameworks at startup.

**Comment by Goldziher** [comment]
Youre welcome to add a PR.

**Comment by k4black** [comment]
Not sure it will be easy to implement it without benchmarking design changes. But I'll work on it

**Comment by Goldziher** [comment]
> Not sure it will be easy to implement it without benchmarking design changes. But I'll work on it

Cool. You're welcome to change stuff - if the result is better 😉
